### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by calebkrauter** [GoodBadChad/good-bad-chad-br#67]
README should have specific details and resources about the project listed in a neat fashion. Update with short description of project, how to run project locally, where the project is deployed, list of references to the Developers and primary resources used.

**Comment by coltenkrauter** [comment]
What were you gonna update in the README?

**Comment by calebkrauter** [comment]
This appears to be a mistake, I intended to PR changes. I'll take a look soon

**Comment by calebkrauter** [comment]
Thanks for the comment! Still getting used to using issues. I'll update that!

**Comment by calebkrauter** [comment]
README up to date.
